# Generated by Django 5.1.7 on 2025-03-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='fallacy_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
